INSERT INTO ACCOUNT (ID, USERNAME,PASSWORD,NICKNAME,ACTIVATED)
 VALUES (1, 'admin', '$2a$10$w3jqc54wmRtvfrvcvdG6SuclMZVg7uvhZvhH4nRo0/MaKWj2CWkHm','YOUNG',1);

INSERT INTO AUTHORITY (ID, AUTHORITY_NAME) VALUES (1,'ROLE_USER');
INSERT INTO AUTHORITY (ID, AUTHORITY_NAME) VALUES (2,'ROLE_ADMIN');

INSERT INTO ACCOUNT_AUTHORITY (ACCOUNT_ID,AUTHORITY_ID) VALUES (1,1);
INSERT INTO ACCOUNT_AUTHORITY (ACCOUNT_ID,AUTHORITY_ID) VALUES (1,2);